language: ruby
services:
- redis
rvm:
- 2.6.10
script:
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: BLVUhoIKllEQlVagVbh37alyZ+U/Vx77Pi+8D91CZ9s8e4jJbJcnE6/LSr9gz6zhbvs9riNnnEcEgk9vlXR1xpRNNxL4TElChDLpwZ3NnbABzJ6UVBBefPlPBSyhSE+EQAPKQUQs7RjOvMEaaecvF2yiUFOQdeGu1/ucwYJ5SeYhwOQPDglywFVxu5sYMvwF3+P5NzOI9uENgVVVL/gJSWlvQzmLDkdlKDN9CNXz/xjGc5jkbedfmdM75K6PVUwRkj5zXRvqlf4byivEDER8nO5QpckbzhVOA/usb/FOIadWCpF766lUPgKLSFlVi875w67gVX4sEoP+DdA9H+hPabNhYQs1UHnS1gbwQTJBOLVa8kwm6Q15pq3RY2jmnKhTE1sDBaGJJR38MoTM7ePQPNhVuxcqONrVx9U9hQP98hmcJ3YBrjQZlxAmDmQugbuud50/fWivIoWMU+hzAqWw8lzNGTfQ9iqgO2wnATkGzRqx0eh9V1E5Z+MUIc2llFSVoqNera6Kpq1sDDe8WkCoUrt2agYMmTS2hQr1Vi7x+lGaPy1G3x12PiTpkCc3SCPoRvLEMxsU5GMtv0Y6SwYHogj3WsDwa/2Xfr3AMd3DDUnOBSXKCn0ComnQiDCZzOUTU+zM4MEHMVp4UVM7Iwjic7K05dMsSjwrwNh3XSGk4F0=
  app: api-dashboard-staging
